### ISSUE TITLE
confirmation dialog would not pop up with Logseq version 0.10.2

### ISSUE THREAD

**Issue by penguin12k** [YU000jp/logseq-plugin-confirmation-done-task#49]
Hello, I updated Logseq to version 0.10.2, and then when I mark a task as DONE, nothing happens, the confirmation dialog is not popping up. 

Is there anywhere I could find a log file of this plugin and upload here?

**Comment by penguin12k** [comment]
I downgraded Logseq to version 0.10.1 and this issue is not happening again.

**Comment by YU000jp** [comment]
I also confirmed that it doesn't work.

The cause is still unknown. I will check out and test Logseq version 0.10.2.
https://github.com/logseq/logseq/pull/10722
https://github.com/logseq/logseq/pull/10399

**Comment by YU000jp** [comment]
I have released a new version. In order to correspond to the new version, changes related to character input will be made. Please let me know if you are experiencing any particular slow input symptoms.

**Comment by penguin12k** [comment]
@YU000jp Hey, I tried version 1.12.2, with both Logseq v0.10.2 & v1.10.3, the confirmation dialog still not appearing.
slow input symptons? no, I use chinese and english, typing both characters are as fast as usual.
